### ISSUE TITLE
Namespace doesn't match with manifest class

### ISSUE THREAD

**Issue by lmachens** [overwolf/overwolf-plugins#11]
Hi,
it looks like the `class` in the sample `manifest.json` files are different than the `namespace` of the plugins.

Example:
https://github.com/overwolf/overwolf-plugins/blob/aba8c86323e03edf8013035561bb678340f316be/sample_apps/process_manager/manifest.json#L33-L36

It says `com.overwolf.net.ProcessManager`.

But in the plugin, the namespace is `com.overwolf.com.overwolf.procmgr`.

https://github.com/overwolf/overwolf-plugins/blob/aba8c86323e03edf8013035561bb678340f316be/plugins/process_manager/process_manager.cs#L14

The correct namespace would be `com.overwolf.net`.
Or the manifest `class` is not correct, which would be `com.overwolf.com.overwolf.procmgr.ProcessManager`.

The same issue appears in other plugins.
It looks like the DLLs in the samples are from a different version than the plugin folders.

**Comment by OdedItkinOW** [comment]
Looks like an issue, will be checked more thoroughly and fixed in the next refactor for this repo
