### ISSUE TITLE
simpleIOPlugin missing documentation for listDirectory

### ISSUE THREAD

**Issue by Colorfulstan** [overwolf/overwolf-plugins#4]
listDirectory is not included in the documentation

**Comment by Noobay** [comment]
heh, you are right! (that's why i created listFiles in my fork, didn't notice it)

**Comment by Noobay** [comment]
a documentation for listDirectory can be found here https://github.com/Noobay/overwolf-plugins/tree/master/simple-io-plugin

**Comment by Colorfulstan** [comment]
God please don't let this become a split repository...all the overwolf documentation and scattered ressources and information is a pain already.

But thanks for your effort @Noobay anyways
